language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # TravisCI doesn't have 3.7 atm https://github.com/travis-ci/travis-ci/issues/9815
  - "pypy"
# command to install dependencies
install:
  - pip install -U setuptools
  - python setup.py install
# command to run tests
script: python setup.py test
